[build]
  command   = "npm install && npm run build"
  publish   = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://fvtrwovquavoyakiczrv.supabase.co"
  VITE_SUPABASE_KEY = "sb_publishable_lELYDMRcDddwfiruCyKxCg_uHAhdhBb"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
